### PR TITLE
🙈 (single-binary-benchmark) Add .gitignore

### PR DESCRIPTION
**Pull request by Hayao0819**

### CODE REVIEW

**Comment by Comamoca** [comment]
Thanks for PR!
`.gitignore` is can recognition at project root.
So, those diff are can simplify. Like this.

```gitignore
out_*
*.md
```
Can you change PR like above?

**Comment by Hayao0819** [comment]
I have considered the pattern which you say however, I thought that the one I sent is better because of the keep of independence in each implements.

**Comment by Hayao0819** [comment]
How about the following?

```gitignore
reports/*.md
*/out_*
```

**Comment by Comamoca** [comment]
LGTM

**Pull request closed without merging**
